# SPDX-FileCopyrightText: 2023 Justin Hammond <justin@dynam.ac>
#
# SPDX-License-Identifier: MIT

DESCRIPTION = "A collection of plugins to handle mobipocket files"
SUMMARY = "A collection of plugins to handle mobipocket files"
HOMEPAGE = "https://invent.kde.org/graphics/kdegraphics-mobipocket"
LICENSE = "GPL-2.0-or-later"
LIC_FILES_CHKSUM = "file://COPYING;md5=751419260aa954499f7abaabaa882bbe"

inherit cmake_plasma


DEPENDS = " \
"

